CREATE TABLE IF NOT EXISTS producto (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    precio DOUBLE PRECISION NOT NULL,
    categoria VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);
